import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar";
import { Nunito_Sans } from 'next/font/google';

import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

*/

const nunitoSans = Nunito_Sans({
  subsets: ['latin'], // Subconjuntos que necesitas (latin es común)
  weight: ['400', '700'], // Pesos que planeas usar
  variable: '--font-nunito-sans', // Nombre de la variable CSS personalizada
});

export const metadata: Metadata = {
  title: "Ingenieria del Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunitoSans.className}
        >
        {children}

        {/*
           <SidebarProvider>
           <AppSidebar />
           <SidebarTrigger />
           </SidebarProvider>
            */}
      </body>
    </html>
  );
}
